name: flutter_maps
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  custom_info_window: ^1.0.1
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  nock: ^1.2.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
